//! Universal Operational Item Domain Model and 6-Stage Lifecycle State Machine.
//!
//! Governs the lifecycle of cross-functional enterprise requests:
//! Captured -> Sandboxed -> ContractVerified -> HumanApproved -> Promoted.

use crate::operational_domain::{DomainPayload, OperationalDomainTag};
use crate::{ExodusError, MigrationDebt, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// 6-Stage Universal Closed-Loop Lifecycle State.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Default,
)]
#[serde(rename_all = "snake_case")]
pub enum OperationalLifecycleState {
    /// Stage 1: Captured payload ingested and assigned domain routing tag (#tags).
    #[default]
    Captured,
    /// Stage 2: Sandboxed in isolated Git worktree or shadow state.
    Sandboxed,
    /// Stage 4: Deterministic contract validation completed successfully.
    ContractVerified,
    /// Fallback stage: Contract validation passed with explicit recorded debt.
    Degraded,
    /// Stage 5: Authorized human approver signed off in Review UI.
    HumanApproved,
    /// Stage 6: Promoted to permanent organizational memory / CASE fixture.
    Promoted,
    /// Terminal rejection stage.
    Rejected,
}

impl std::fmt::Display for OperationalLifecycleState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Captured => write!(f, "Captured"),
            Self::Sandboxed => write!(f, "Sandboxed"),
            Self::ContractVerified => write!(f, "ContractVerified"),
            Self::Degraded => write!(f, "Degraded"),
            Self::HumanApproved => write!(f, "HumanApproved"),
            Self::Promoted => write!(f, "Promoted"),
            Self::Rejected => write!(f, "Rejected"),
        }
    }
}

/// Outcome of a single deterministic rule check during contract verification.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuleVerificationResult {
    pub rule_name: String,
    pub passed: bool,
    pub details: String,
}

/// Comprehensive report generated by stage 4 contract verification.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContractVerificationReport {
    pub verified_at: DateTime<Utc>,
    pub passed: bool,
    pub rule_results: Vec<RuleVerificationResult>,
    pub summary: String,
    pub debt: Vec<MigrationDebt>,
}

impl ContractVerificationReport {
    pub fn success(summary: impl Into<String>, rule_results: Vec<RuleVerificationResult>) -> Self {
        Self {
            verified_at: Utc::now(),
            passed: true,
            rule_results,
            summary: summary.into(),
            debt: Vec::new(),
        }
    }

    pub fn degraded(
        summary: impl Into<String>,
        rule_results: Vec<RuleVerificationResult>,
        debt: Vec<MigrationDebt>,
    ) -> Self {
        Self {
            verified_at: Utc::now(),
            passed: true,
            rule_results,
            summary: summary.into(),
            debt,
        }
    }

    pub fn failure(summary: impl Into<String>, rule_results: Vec<RuleVerificationResult>) -> Self {
        Self {
            verified_at: Utc::now(),
            passed: false,
            rule_results,
            summary: summary.into(),
            debt: Vec::new(),
        }
    }
}

/// Tamper-evident audit log entry tracking state transitions and actor actions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuditLogEntry {
    pub timestamp: DateTime<Utc>,
    pub actor: String,
    pub action: String,
    pub details: String,
}

/// Diagnostic breakdown explaining why a prompt failed to achieve its unit goal.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UnitPromptDiagnostic {
    pub stage_failed: String,
    pub prompt_goal: String,
    pub execution_divergence: String,
    pub failure_reason: String,
    #[serde(default)]
    pub error_snippet: Option<String>,
    #[serde(default)]
    pub suggested_refinement: Option<String>,
}

/// Universal operational unit bridging business requests and execution mechanics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OperationalItem {
    /// Unique identifier: `op-<uuidv7>`
    pub id: String,
    /// Operational domain tag (#prod-bug, #crm-request, #survey-mapping)
    pub domain_tag: OperationalDomainTag,
    /// Brief descriptive title
    pub title: String,
    /// Detailed description or request context
    pub description: String,
    /// Current lifecycle state
    pub state: OperationalLifecycleState,
    /// Timestamp when item was ingested
    pub created_at: DateTime<Utc>,
    /// Timestamp of most recent mutation
    pub updated_at: DateTime<Utc>,
    /// Submitting actor / system
    pub requester: String,
    /// Human reviewer who approved the item, if approved
    pub approver: Option<String>,
    /// Promoted case ID (e.g. `CASE-2026-0042`), if promoted
    pub promoted_case_id: Option<String>,
    /// Reference to sandboxed execution environment (worktree path or branch)
    pub sandbox_ref: Option<String>,
    /// Domain-specific payload
    pub payload: DomainPayload,
    /// Latest verification report, if verified
    pub verification_report: Option<ContractVerificationReport>,
    /// Sequential audit log of all actions on this item
    pub audit_trail: Vec<AuditLogEntry>,
    /// Explicit migration or operational debt items
    pub debt: Vec<MigrationDebt>,
    /// Optional developer prompt attached to this unit
    #[serde(default)]
    pub prompt: Option<String>,
    /// Macro system goal to which this unit attaches
    #[serde(default)]
    pub system_goal: Option<String>,
    /// User-editable tags (e.g. #auth, #latency, #security)
    #[serde(default)]
    pub tags: Vec<String>,
    /// Mapped Change Graph symbol/file IDs
    #[serde(default)]
    pub graph_mappings: Vec<String>,
    /// Diagnostic breakdown if verification/prompt failed or degraded
    #[serde(default)]
    pub unit_diagnostic: Option<UnitPromptDiagnostic>,
}

impl OperationalItem {
    /// Create a new operational item in Stage 1: Captured.
    pub fn new(
        title: impl Into<String>,
        description: impl Into<String>,
        requester: impl Into<String>,
        payload: DomainPayload,
    ) -> Self {
        let now = Utc::now();
        let domain_tag = payload.domain_tag();
        let id = format!("op-{}", uuid::Uuid::now_v7());
        let requester_str = requester.into();

        let initial_audit = AuditLogEntry {
            timestamp: now,
            actor: requester_str.clone(),
            action: "INGEST_EVENT".to_string(),
            details: format!(
                "Operational item ingested into domain {} with state Captured",
                domain_tag
            ),
        };

        Self {
            id,
            domain_tag,
            title: title.into(),
            description: description.into(),
            state: OperationalLifecycleState::Captured,
            created_at: now,
            updated_at: now,
            requester: requester_str,
            approver: None,
            promoted_case_id: None,
            sandbox_ref: None,
            payload,
            verification_report: None,
            audit_trail: vec![initial_audit],
            debt: Vec::new(),
            prompt: None,
            system_goal: None,
            tags: vec![domain_tag.to_string()],
            graph_mappings: Vec::new(),
            unit_diagnostic: None,
        }
    }

    /// Advance item to Stage 3: Sandboxed.
    pub fn mark_sandboxed(&mut self, actor: &str, sandbox_ref: &str) -> Result<()> {
        if matches!(
            self.state,
            OperationalLifecycleState::HumanApproved
                | OperationalLifecycleState::Promoted
                | OperationalLifecycleState::Rejected
        ) {
            return Err(ExodusError::OperationalError(format!(
                "Cannot sandbox item {} in terminal or approved state: {}",
                self.id, self.state
            )));
        }

        self.state = OperationalLifecycleState::Sandboxed;
        self.sandbox_ref = Some(sandbox_ref.to_string());
        self.updated_at = Utc::now();
        self.audit_trail.push(AuditLogEntry {
            timestamp: self.updated_at,
            actor: actor.to_string(),
            action: "ALLOCATE_SANDBOX".to_string(),
            details: format!("Isolated execution sandbox allocated at: {}", sandbox_ref),
        });
        Ok(())
    }

    /// Advance item to Stage 4: ContractVerified or Degraded.
    pub fn record_verification(
        &mut self,
        actor: &str,
        report: ContractVerificationReport,
    ) -> Result<()> {
        if self.state != OperationalLifecycleState::Sandboxed {
            return Err(ExodusError::OperationalError(format!(
                "Item {} must be Sandboxed before contract verification (current: {})",
                self.id, self.state
            )));
        }

        self.updated_at = Utc::now();
        if !report.passed {
            self.state = OperationalLifecycleState::Rejected;
            self.audit_trail.push(AuditLogEntry {
                timestamp: self.updated_at,
                actor: actor.to_string(),
                action: "VERIFICATION_FAILED".to_string(),
                details: format!("Verification failed: {}", report.summary),
            });
            self.verification_report = Some(report);
            return Ok(());
        }

        if !report.debt.is_empty() {
            self.state = OperationalLifecycleState::Degraded;
            self.debt.extend(report.debt.clone());
            self.audit_trail.push(AuditLogEntry {
                timestamp: self.updated_at,
                actor: actor.to_string(),
                action: "VERIFICATION_DEGRADED".to_string(),
                details: format!(
                    "Passed with {} recorded debt items: {}",
                    report.debt.len(),
                    report.summary
                ),
            });
        } else {
            self.state = OperationalLifecycleState::ContractVerified;
            self.audit_trail.push(AuditLogEntry {
                timestamp: self.updated_at,
                actor: actor.to_string(),
                action: "VERIFICATION_PASSED".to_string(),
                details: format!("Deterministic contract verified: {}", report.summary),
            });
        }

        self.verification_report = Some(report);
        Ok(())
    }

    /// Stage 5: Human approval through review gate.
    pub fn approve(&mut self, approver: &str, notes: &str) -> Result<()> {
        if !matches!(
            self.state,
            OperationalLifecycleState::ContractVerified | OperationalLifecycleState::Degraded
        ) {
            return Err(ExodusError::OperationalError(format!(
                "Cannot approve item {}: must be ContractVerified or Degraded (current: {})",
                self.id, self.state
            )));
        }

        self.state = OperationalLifecycleState::HumanApproved;
        self.approver = Some(approver.to_string());
        self.updated_at = Utc::now();
        self.audit_trail.push(AuditLogEntry {
            timestamp: self.updated_at,
            actor: approver.to_string(),
            action: "HUMAN_APPROVAL".to_string(),
            details: format!("Approved by human reviewer: {}", notes),
        });
        Ok(())
    }

    /// Stage 6: Promote verified and approved resolution to organizational memory.
    pub fn promote(&mut self, promoter: &str, case_id: &str) -> Result<()> {
        if self.state != OperationalLifecycleState::HumanApproved {
            return Err(ExodusError::OperationalError(format!(
                "Cannot promote item {}: must be HumanApproved first (current: {})",
                self.id, self.state
            )));
        }

        self.state = OperationalLifecycleState::Promoted;
        self.promoted_case_id = Some(case_id.to_string());
        self.updated_at = Utc::now();
        self.audit_trail.push(AuditLogEntry {
            timestamp: self.updated_at,
            actor: promoter.to_string(),
            action: "KNOWLEDGE_PROMOTION".to_string(),
            details: format!("Promoted to reusable case fixture: {}", case_id),
        });
        Ok(())
    }

    /// Reject item explicitly.
    pub fn reject(&mut self, actor: &str, reason: &str) -> Result<()> {
        if self.state == OperationalLifecycleState::Promoted {
            return Err(ExodusError::OperationalError(format!(
                "Cannot reject already promoted item {}",
                self.id
            )));
        }

        self.state = OperationalLifecycleState::Rejected;
        self.updated_at = Utc::now();
        self.audit_trail.push(AuditLogEntry {
            timestamp: self.updated_at,
            actor: actor.to_string(),
            action: "REJECTED".to_string(),
            details: format!("Rejected: {}", reason),
        });
        Ok(())
    }

    /// Attach or update the developer prompt and optional macro system goal for this unit.
    pub fn attach_prompt(&mut self, prompt: impl Into<String>, system_goal: Option<String>) {
        self.prompt = Some(prompt.into());
        if system_goal.is_some() {
            self.system_goal = system_goal;
        }
        self.updated_at = Utc::now();
        self.audit_trail.push(AuditLogEntry {
            timestamp: self.updated_at,
            actor: "developer".to_string(),
            action: "PROMPT_ATTACHED".to_string(),
            details: format!("Attached developer unit prompt: {:?}", self.prompt),
        });
    }

    /// Update user-editable tags and Change Graph symbol/file mappings.
    pub fn update_tags(&mut self, tags: Vec<String>, graph_mappings: Vec<String>) {
        self.tags = tags;
        self.graph_mappings = graph_mappings;
        self.updated_at = Utc::now();
        self.audit_trail.push(AuditLogEntry {
            timestamp: self.updated_at,
            actor: "operator".to_string(),
            action: "TAGS_UPDATED".to_string(),
            details: format!(
                "Updated {} tags and {} graph mappings",
                self.tags.len(),
                self.graph_mappings.len()
            ),
        });
    }

    /// Record a diagnostic breakdown explaining why a prompt failed to achieve its goal.
    pub fn record_diagnostic(&mut self, diag: UnitPromptDiagnostic) {
        self.unit_diagnostic = Some(diag);
        self.updated_at = Utc::now();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::operational_domain::{CrmRequestPayload, ProdBugPayload};
    use std::path::PathBuf;

    #[test]
    fn test_operational_item_lifecycle_happy_path() {
        let payload = DomainPayload::ProdBug(ProdBugPayload::new(
            "commit-abc1234",
            "NullPointerException at auth.rs:42",
            Some(PathBuf::from("src/auth.rs")),
        ));

        let mut item = OperationalItem::new(
            "Fix NPE in Auth Service",
            "CI failure observed on master branch",
            "ci-agent",
            payload,
        );

        assert_eq!(item.state, OperationalLifecycleState::Captured);
        assert_eq!(item.domain_tag, OperationalDomainTag::ProdBug);

        // Stage 2: Sandbox
        assert!(item
            .mark_sandboxed("worktree-mgr", ".exodus/worktrees/wt-1")
            .is_ok());
        assert_eq!(item.state, OperationalLifecycleState::Sandboxed);

        // Stage 4: Contract Verification
        let report = ContractVerificationReport::success(
            "cargo test pass, 0 compile errors",
            vec![RuleVerificationResult {
                rule_name: "cargo_test".to_string(),
                passed: true,
                details: "test auth::test_login ... ok".to_string(),
            }],
        );
        assert!(item.record_verification("verifier-agent", report).is_ok());
        assert_eq!(item.state, OperationalLifecycleState::ContractVerified);

        // Stage 5: Human Approval
        assert!(item
            .approve("lead-architect", "Diff is clean and passes tests")
            .is_ok());
        assert_eq!(item.state, OperationalLifecycleState::HumanApproved);
        assert_eq!(item.approver.as_deref(), Some("lead-architect"));

        // Stage 6: Promotion
        assert!(item.promote("case-engine", "CASE-2026-0001").is_ok());
        assert_eq!(item.state, OperationalLifecycleState::Promoted);
        assert_eq!(item.promoted_case_id.as_deref(), Some("CASE-2026-0001"));
        assert_eq!(item.audit_trail.len(), 5);
    }

    #[test]
    fn test_approval_forbidden_without_verification() {
        let payload = DomainPayload::CrmRequest(CrmRequestPayload::new(
            "acc-100",
            "Acme Corp",
            120_000.0,
            20.0,
            "Enterprise",
            "SalesLead",
        ));

        let mut item = OperationalItem::new(
            "Enterprise Tier Discount Request",
            "Customer requesting 20% discount on Enterprise renewal",
            "sales-rep",
            payload,
        );

        // Attempting to approve directly from Captured state must fail
        let res = item.approve("vp-sales", "Approved early");
        assert!(res.is_err());
        assert_eq!(item.state, OperationalLifecycleState::Captured);
    }
}
